### ISSUE TITLE
Can't connect on OS X

### ISSUE THREAD

**Issue by isaacroehm** [brandon-rhodes/fopnp#4] opened 2015-01-28 15:26 UTC
Hello,

I got the playground to run on VirtualBox 4.3.20 on OS X by adding a local host adapter in VirtualBox settings and disabling the serial adapter. The host only adapter is set to 192.168.56.1 and I can't change the third octet to anything besides starting with a 5. I try ssh -p 220x brandon@localhost from terminal and am unable to connect. What should I change, need to add etc to get connected?

**Comment by michealbeatty** [comment] 2015-08-05 00:51
I am unable to connect using OS X as well. What is the result of running the ssh command with the -v flag? For example, `ssh -v -p 2201 brandon@localhost`

**Comment by brandon-rhodes** [comment] 2015-08-17 18:20
All right!

After months of trying to work around this problem — and after several conversations with people who have more experience with virtualization than I do — I have deprecated my original scheme of distributing a bare VirtualBox image and expecting it to run across multiple operating systems correctly, especially with network forwarding turned on.

I have just rebuilt, repackaged, and re-uploaded the Playground as a Vagrant box, because Vagrant had a reputation for doing a better job of supporting cross-platform image support than do any of the raw native back-end mechanisms for virtualization like VirtualBox.

I have amended the Playground instructions to explain starting up a Vagrant box:

https://github.com/brandon-rhodes/fopnp/tree/m/playground

Could you try out the instructions and let me know if they work on your platform and, if not, at which step they fail? Thanks so much!

**Comment by michealbeatty** [comment] 2015-08-17 23:34
Getting a message when running 

`vagrant up --provider virtualbox` 

that the version of Virtualbox I have installed is not supported. I'm running Virtualbox 5.x and only 4.x is supported. I can try rolling back to 4.3 to see if it works.

**Comment by michealbeatty** [comment] 2015-08-17 23:53
...and after downgrading to Virtualbox 4.3 the playground is working fine. Thank you for finding a solution for us.

**Comment by brandon-rhodes** [comment] 2015-08-18 03:50
You are welcome! I am a bit surprised that Vagrant is a bit behind on Virtualbox versions, but given the problems that I myself had with getting a Virtualbox solution working, I would not be surprised if they are stalled on a bug in the 5.x series and are having to wait to upgrade. Thanks for being willing to downgrade to make this test, @amikiri!

I am closing this issue, but either of you is welcome to please open a new one if you have further problems — I hope you are able to enjoy the playground now!

**Comment by risdenk** [comment] 2015-08-18 13:21
@amikiri - You need Vagrant 1.7.3 or higher to work with Virtualbox 5.x. See the changelog here: https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#173-july-10-2015

@brandon-rhodes - The Vagrant box works with the latest version of Vagrant (1.7.4) and Virtualbox (5.0.2) on Mac OS X 10.10.5.

**Comment by michealbeatty** [comment] 2015-08-18 14:12
confirmed that after updating to Vagrant 1.7.4 and Virtualbox 5, I am able to `vagrant up` thanks for the tip @risdenk

**Comment by brandon-rhodes** [comment] 2015-08-18 18:36
Thank you both for your reports! I am re-opening this issue until I update the docs with this information in case anyone else runs into problems with the combination of versions.

And, I am glad that you are both able to access the playground now!

**Comment by brandon-rhodes** [comment] 2015-12-10 13:08
This was resolved in 0d849129 when I updated the documentation — but I forgot to come back here and close the issue! :)

**Closed as completed by brandon-rhodes** 2015-12-10 13:08 UTC
